package testing;

/*Generated by MPS */

import jetbrains.mps.MPSLaunch;
import model.UnitTest;
import org.junit.Test;

@MPSLaunch
public class BedragOuderdomspensioen extends UnitTest {
  @Test
  public void Hoogte_AOW_met_partner_voor_de_AOW_met_loonheffingskorting() {
    UnitTest.test("NewSolution.testing.Bedrag ouderdomspensioen.Hoogte AOW met partner voor de AOW met loonheffingskorting", "519085519417888479", "C:/Users/jekea01/MPSProjects/PRA - Pensioen Case Project", "r:3a1c14c5-b06d-4194-97ee-d53d0fdd17d6(testing)", myEnvironment);
  }
  @Test
  public void Hoogte_AOW_zonder_partner_voor_de_AOW_met_loonheffingskorting() {
    UnitTest.test("NewSolution.testing.Bedrag ouderdomspensioen.Hoogte AOW zonder partner voor de AOW met loonheffingskorting", "519085519417903978", "C:/Users/jekea01/MPSProjects/PRA - Pensioen Case Project", "r:3a1c14c5-b06d-4194-97ee-d53d0fdd17d6(testing)", myEnvironment);
  }
}
