package testing;

/*Generated by MPS */

import jetbrains.mps.MPSLaunch;
import model.UnitTest;
import org.junit.Test;

@MPSLaunch
public class BerekeningVoorPercentageRechtOpOuderdomspensioen extends UnitTest {
  @Test
  public void berekening_recht_op_ouderdomspensioen_01() {
    UnitTest.test("NewSolution.testing.Berekening voor percentage recht op ouderdomspensioen.berekening recht op ouderdomspensioen 01", "519085519418080370", "C:/Users/jekea01/MPSProjects/PRA - Pensioen Case Project", "r:3a1c14c5-b06d-4194-97ee-d53d0fdd17d6(testing)", myEnvironment);
  }
  @Test
  public void berekening_recht_op_ouderdomspensioen_02() {
    UnitTest.test("NewSolution.testing.Berekening voor percentage recht op ouderdomspensioen.berekening recht op ouderdomspensioen 02", "519085519418156320", "C:/Users/jekea01/MPSProjects/PRA - Pensioen Case Project", "r:3a1c14c5-b06d-4194-97ee-d53d0fdd17d6(testing)", myEnvironment);
  }
}
