package testing;

/*Generated by MPS */

import jetbrains.mps.MPSLaunch;
import model.UnitTest;
import org.junit.Test;

@MPSLaunch
public class FlowtestHoogteBedragBrutoEnNettoOuderdomspensioen extends UnitTest {
  @Test
  public void berekening_bruto_netto_ouderdomspensioen_met_partner_excl_korting() {
    UnitTest.test("NewSolution.testing.Flow testing.Flowtest hoogte bedrag bruto en netto ouderdomspensioen.berekening bruto netto ouderdomspensioen met partner excl korting", "519085519418190263", "C:/Users/jekea01/MPSProjects/PRA - Pensioen Case Project", "r:3a1c14c5-b06d-4194-97ee-d53d0fdd17d6(testing)", myEnvironment);
  }
  @Test
  public void berekening_bruto_netto_ouderdomspensioen_zonder_partner_excl_korting() {
    UnitTest.test("NewSolution.testing.Flow testing.Flowtest hoogte bedrag bruto en netto ouderdomspensioen.berekening bruto netto ouderdomspensioen zonder partner excl korting", "519085519418193748", "C:/Users/jekea01/MPSProjects/PRA - Pensioen Case Project", "r:3a1c14c5-b06d-4194-97ee-d53d0fdd17d6(testing)", myEnvironment);
  }
  @Test
  public void berekening_bruto_netto_ouderdomspensioen_met_partner_incl_korting_10_() {
    UnitTest.test("NewSolution.testing.Flow testing.Flowtest hoogte bedrag bruto en netto ouderdomspensioen.berekening bruto netto ouderdomspensioen met partner incl korting 10%", "519085519418195676", "C:/Users/jekea01/MPSProjects/PRA - Pensioen Case Project", "r:3a1c14c5-b06d-4194-97ee-d53d0fdd17d6(testing)", myEnvironment);
  }
}
