package testing;

/*Generated by MPS */

import jetbrains.mps.MPSLaunch;
import model.UnitTest;
import org.junit.Test;

@MPSLaunch
public class FlowtestVoorBerekeningTotaalAOW extends UnitTest {
  @Test
  public void berekening_bruto_netto_ouderdomspensioen_met_partner_excl_korting() {
    UnitTest.test("NewSolution.testing.Flow testing.Flowtest voor berekening totaal AOW.berekening bruto netto ouderdomspensioen met partner excl korting", "1727859032467246727", "C:/Users/jekea01/MPSProjects/PRA - Pensioen Case Project", "r:3a1c14c5-b06d-4194-97ee-d53d0fdd17d6(testing)", myEnvironment);
  }
}
