package testing;

/*Generated by MPS */

import jetbrains.mps.MPSLaunch;
import model.UnitTest;
import org.junit.Test;

@MPSLaunch
public class PensioengerechtigdeLeeftijdVanaf2026 extends UnitTest {
  @Test
  public void _001() {
    UnitTest.test("NewSolution.testing.Pensioengerechtigde leeftijd vanaf 2026.001", "4038074786039914351", "C:/Users/jekea01/MPSProjects/PRA - Pensioen Case Project", "r:3a1c14c5-b06d-4194-97ee-d53d0fdd17d6(testing)", myEnvironment);
  }
  @Test
  public void _002() {
    UnitTest.test("NewSolution.testing.Pensioengerechtigde leeftijd vanaf 2026.002", "4038074786039964219", "C:/Users/jekea01/MPSProjects/PRA - Pensioen Case Project", "r:3a1c14c5-b06d-4194-97ee-d53d0fdd17d6(testing)", myEnvironment);
  }
  @Test
  public void _003() {
    UnitTest.test("NewSolution.testing.Pensioengerechtigde leeftijd vanaf 2026.003", "878861464539562845", "C:/Users/jekea01/MPSProjects/PRA - Pensioen Case Project", "r:3a1c14c5-b06d-4194-97ee-d53d0fdd17d6(testing)", myEnvironment);
  }
}
