package testing;

/*Generated by MPS */

import jetbrains.mps.MPSLaunch;
import model.UnitTest;
import org.junit.Test;

@MPSLaunch
public class PensioengerechtigeDatumTesten extends UnitTest {
  @Test
  public void geboortedatum_30_11_1948() {
    UnitTest.test("NewSolution.testing.Pensioengerechtige datum testen.geboortedatum 30-11-1948", "7584460524975903416", "C:/Users/jekea01/MPSProjects/PRA - Pensioen Case Project", "r:3a1c14c5-b06d-4194-97ee-d53d0fdd17d6(testing)", myEnvironment);
  }
  @Test
  public void geboortedatum_1_12_1948() {
    UnitTest.test("NewSolution.testing.Pensioengerechtige datum testen.geboortedatum 1-12-1948", "7321771930338766666", "C:/Users/jekea01/MPSProjects/PRA - Pensioen Case Project", "r:3a1c14c5-b06d-4194-97ee-d53d0fdd17d6(testing)", myEnvironment);
  }
  @Test
  public void geboortedatum_1_4_1950() {
    UnitTest.test("NewSolution.testing.Pensioengerechtige datum testen.geboortedatum 1-4-1950", "7584460524975961582", "C:/Users/jekea01/MPSProjects/PRA - Pensioen Case Project", "r:3a1c14c5-b06d-4194-97ee-d53d0fdd17d6(testing)", myEnvironment);
  }
  @Test
  public void geboortedatum_1_10_1950() {
    UnitTest.test("NewSolution.testing.Pensioengerechtige datum testen.geboortedatum 1-10-1950", "7584460524976019936", "C:/Users/jekea01/MPSProjects/PRA - Pensioen Case Project", "r:3a1c14c5-b06d-4194-97ee-d53d0fdd17d6(testing)", myEnvironment);
  }
  @Test
  public void geboortedatum_1_1_1951() {
    UnitTest.test("NewSolution.testing.Pensioengerechtige datum testen.geboortedatum 1-1-1951", "7321771930339187913", "C:/Users/jekea01/MPSProjects/PRA - Pensioen Case Project", "r:3a1c14c5-b06d-4194-97ee-d53d0fdd17d6(testing)", myEnvironment);
  }
  @Test
  public void geboortedatum_1_10_1952() {
    UnitTest.test("NewSolution.testing.Pensioengerechtige datum testen.geboortedatum 1-10-1952", "7321771930339179547", "C:/Users/jekea01/MPSProjects/PRA - Pensioen Case Project", "r:3a1c14c5-b06d-4194-97ee-d53d0fdd17d6(testing)", myEnvironment);
  }
  @Test
  public void geboortedatum_29_2_1956__schrikkeljaar_() {
    UnitTest.test("NewSolution.testing.Pensioengerechtige datum testen.geboortedatum 29-2-1956 (schrikkeljaar)", "7321771930339576135", "C:/Users/jekea01/MPSProjects/PRA - Pensioen Case Project", "r:3a1c14c5-b06d-4194-97ee-d53d0fdd17d6(testing)", myEnvironment);
  }
  @Test
  public void geboortedatum_1_6_1956() {
    UnitTest.test("NewSolution.testing.Pensioengerechtige datum testen.geboortedatum 1-6-1956", "7584460524975963914", "C:/Users/jekea01/MPSProjects/PRA - Pensioen Case Project", "r:3a1c14c5-b06d-4194-97ee-d53d0fdd17d6(testing)", myEnvironment);
  }
  @Test
  public void geboortedamum_11_12_1958() {
    UnitTest.test("NewSolution.testing.Pensioengerechtige datum testen.geboortedamum 11-12-1958", "7321771930339113336", "C:/Users/jekea01/MPSProjects/PRA - Pensioen Case Project", "r:3a1c14c5-b06d-4194-97ee-d53d0fdd17d6(testing)", myEnvironment);
  }
  @Test
  public void geboortedamum_29_2_1960__schrikkeljaar_() {
    UnitTest.test("NewSolution.testing.Pensioengerechtige datum testen.geboortedamum 29-2-1960 (schrikkeljaar)", "7321771930339585683", "C:/Users/jekea01/MPSProjects/PRA - Pensioen Case Project", "r:3a1c14c5-b06d-4194-97ee-d53d0fdd17d6(testing)", myEnvironment);
  }
  @Test
  public void geboortedamum_11_12_1960() {
    UnitTest.test("NewSolution.testing.Pensioengerechtige datum testen.geboortedamum 11-12-1960", "7321771930339154359", "C:/Users/jekea01/MPSProjects/PRA - Pensioen Case Project", "r:3a1c14c5-b06d-4194-97ee-d53d0fdd17d6(testing)", myEnvironment);
  }
  @Test
  public void geboortedamum_11_12_1961() {
    UnitTest.test("NewSolution.testing.Pensioengerechtige datum testen.geboortedamum 11-12-1961", "878861464539586272", "C:/Users/jekea01/MPSProjects/PRA - Pensioen Case Project", "r:3a1c14c5-b06d-4194-97ee-d53d0fdd17d6(testing)", myEnvironment);
  }
}
