package testing;

/*Generated by MPS */

import jetbrains.mps.MPSLaunch;
import model.UnitTest;
import org.junit.Test;

@MPSLaunch
public class TestRegelgroepBerekningAOWToeslag extends UnitTest {
  @Test
  public void _001() {
    UnitTest.test("NewSolution.testing.Test - regelgroep Berekning AOW toeslag.001", "1727859032467259560", "C:/Users/jekea01/MPSProjects/PRA - Pensioen Case Project", "r:3a1c14c5-b06d-4194-97ee-d53d0fdd17d6(testing)", myEnvironment);
  }
  @Test
  public void _002() {
    UnitTest.test("NewSolution.testing.Test - regelgroep Berekning AOW toeslag.002", "1727859032467261250", "C:/Users/jekea01/MPSProjects/PRA - Pensioen Case Project", "r:3a1c14c5-b06d-4194-97ee-d53d0fdd17d6(testing)", myEnvironment);
  }
}
